config/routes.rb
Rails.application.routes.draw do
  
  resources "contacts", only: [:new, :create]
  
  resources :consultants

  resources :associates

  get 'comments/create'

  get 'comments/destroy'

  resources :posts, :path => 'blog' do
    resources :comments
  end

  get 'careers/associate'

  get 'careers/independent'

  get 'whatwedo/social'

  get 'whatwedo/consulting'

  get 'whatwedo/technology'

  get 'home/index'

  get 'aboutus' => "home#aboutus"

  get 'whatwedo' => "home#whatwedo"

  get 'careers' => "home#careers"
  
  get 'starter' => "home#starter"
  
  get 'agrinvest' => "home#agrinvest"
  
  get 'gaae' => "home#gaae"
  
  get 'organic' => "home#organic"

  root 'home#index'

end

app/models/consultant.rb
class Consultant < ActiveRecord::Base
end

app/controllers/consultants_controller.rb
class ConsultantsController < ApplicationController
  before_action :set_consultant, only: [:show, :edit, :update, :destroy]

  # GET /consultants
  # GET /consultants.json
  def index
    @consultants = Consultant.all
  end

  # GET /consultants/1
  # GET /consultants/1.json
  def show
  end

  # GET /consultants/new
  def new
    @consultant = Consultant.new
  end

  # GET /consultants/1/edit
  def edit
  end

  # POST /consultants
  # POST /consultants.json
  def create
    @consultant = Consultant.new(consultant_params)

    respond_to do |format|
      if @consultant.save
        format.html { redirect_to @consultant, notice: 'Consultant was successfully created.' }
        format.json { render :show, status: :created, location: @consultant }
      else
        format.html { render :new }
        format.json { render json: @consultant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /consultants/1
  # PATCH/PUT /consultants/1.json
  def update
    respond_to do |format|
      if @consultant.update(consultant_params)
        format.html { redirect_to @consultant, notice: 'Consultant was successfully updated.' }
        format.json { render :show, status: :ok, location: @consultant }
      else
        format.html { render :edit }
        format.json { render json: @consultant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /consultants/1
  # DELETE /consultants/1.json
  def destroy
    @consultant.destroy
    respond_to do |format|
      format.html { redirect_to consultants_url, notice: 'Consultant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_consultant
      @consultant = Consultant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def consultant_params
      params.require(:consultant).permit(:surname, :other_names, :dob, :contact_add, :sec_institution, :sec_certificate, :sec_date, :uni_institution, :uni_certificate, :uni_date, :other_institution, :other_certificate, :other_date, :personal_statement, :hobbies, :telephone, :email, :company_name, :company_business, :area_of_interest, :registered, :registration_details)
    end
end

app/helpers/consultants_helper.rb
module ConsultantsHelper
end

app/views/consultants/_form.html.erb
<%= simple_form_for(@consultant) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :surname %>
    <%= f.input :other_names %>
    <%= f.input :dob %>
    <%= f.input :contact_add %>
    <%= f.input :sec_institution %>
    <%= f.input :sec_certificate %>
    <%= f.input :sec_date %>
    <%= f.input :uni_institution %>
    <%= f.input :uni_certificate %>
    <%= f.input :uni_date %>
    <%= f.input :other_institution %>
    <%= f.input :other_certificate %>
    <%= f.input :other_date %>
    <%= f.input :personal_statement %>
    <%= f.input :hobbies %>
    <%= f.input :telephone %>
    <%= f.input :email %>
    <%= f.input :company_name %>
    <%= f.input :company_business %>
    <%= f.input :area_of_interest %>
    <%= f.input :registered %>
    <%= f.input :registration_details %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/consultants/edit.html.erb
<h1>Editing consultant</h1>

<%= render 'form' %>

<%= link_to 'Show', @consultant %> |
<%= link_to 'Back', consultants_path %>

app/views/consultants/index.html.erb
<h1>Listing consultants</h1>

<table>
  <thead>
    <tr>
      <th>Surname</th>
      <th>Other names</th>
      <th>Dob</th>
      <th>Contact add</th>
      <th>Sec institution</th>
      <th>Sec certificate</th>
      <th>Sec date</th>
      <th>Uni institution</th>
      <th>Uni certificate</th>
      <th>Uni date</th>
      <th>Other institution</th>
      <th>Other certificate</th>
      <th>Other date</th>
      <th>Personal statement</th>
      <th>Hobbies</th>
      <th>Telephone</th>
      <th>Email</th>
      <th>Company name</th>
      <th>Company business</th>
      <th>Area of interest</th>
      <th>Registered</th>
      <th>Registration details</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @consultants.each do |consultant| %>
      <tr>
        <td><%= consultant.surname %></td>
        <td><%= consultant.other_names %></td>
        <td><%= consultant.dob %></td>
        <td><%= consultant.contact_add %></td>
        <td><%= consultant.sec_institution %></td>
        <td><%= consultant.sec_certificate %></td>
        <td><%= consultant.sec_date %></td>
        <td><%= consultant.uni_institution %></td>
        <td><%= consultant.uni_certificate %></td>
        <td><%= consultant.uni_date %></td>
        <td><%= consultant.other_institution %></td>
        <td><%= consultant.other_certificate %></td>
        <td><%= consultant.other_date %></td>
        <td><%= consultant.personal_statement %></td>
        <td><%= consultant.hobbies %></td>
        <td><%= consultant.telephone %></td>
        <td><%= consultant.email %></td>
        <td><%= consultant.company_name %></td>
        <td><%= consultant.company_business %></td>
        <td><%= consultant.area_of_interest %></td>
        <td><%= consultant.registered %></td>
        <td><%= consultant.registration_details %></td>
        <td><%= link_to 'Show', consultant %></td>
        <td><%= link_to 'Edit', edit_consultant_path(consultant) %></td>
        <td><%= link_to 'Destroy', consultant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Consultant', new_consultant_path %>

app/views/consultants/new.html.erb
<h1>New consultant</h1>

<%= render 'form' %>

<%= link_to 'Back', consultants_path %>

app/views/consultants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Surname:</strong>
  <%= @consultant.surname %>
</p>

<p>
  <strong>Other names:</strong>
  <%= @consultant.other_names %>
</p>

<p>
  <strong>Dob:</strong>
  <%= @consultant.dob %>
</p>

<p>
  <strong>Contact add:</strong>
  <%= @consultant.contact_add %>
</p>

<p>
  <strong>Sec institution:</strong>
  <%= @consultant.sec_institution %>
</p>

<p>
  <strong>Sec certificate:</strong>
  <%= @consultant.sec_certificate %>
</p>

<p>
  <strong>Sec date:</strong>
  <%= @consultant.sec_date %>
</p>

<p>
  <strong>Uni institution:</strong>
  <%= @consultant.uni_institution %>
</p>

<p>
  <strong>Uni certificate:</strong>
  <%= @consultant.uni_certificate %>
</p>

<p>
  <strong>Uni date:</strong>
  <%= @consultant.uni_date %>
</p>

<p>
  <strong>Other institution:</strong>
  <%= @consultant.other_institution %>
</p>

<p>
  <strong>Other certificate:</strong>
  <%= @consultant.other_certificate %>
</p>

<p>
  <strong>Other date:</strong>
  <%= @consultant.other_date %>
</p>

<p>
  <strong>Personal statement:</strong>
  <%= @consultant.personal_statement %>
</p>

<p>
  <strong>Hobbies:</strong>
  <%= @consultant.hobbies %>
</p>

<p>
  <strong>Telephone:</strong>
  <%= @consultant.telephone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @consultant.email %>
</p>

<p>
  <strong>Company name:</strong>
  <%= @consultant.company_name %>
</p>

<p>
  <strong>Company business:</strong>
  <%= @consultant.company_business %>
</p>

<p>
  <strong>Area of interest:</strong>
  <%= @consultant.area_of_interest %>
</p>

<p>
  <strong>Registered:</strong>
  <%= @consultant.registered %>
</p>

<p>
  <strong>Registration details:</strong>
  <%= @consultant.registration_details %>
</p>

<%= link_to 'Edit', edit_consultant_path(@consultant) %> |
<%= link_to 'Back', consultants_path %>