config/routes.rb
Rails.application.routes.draw do
  
  resources "contacts", only: [:new, :create]
  
  resources :consultants

  resources :associates

  get 'comments/create'

  get 'comments/destroy'

  resources :posts, :path => 'blog' do
    resources :comments
  end

  get 'careers/associate'

  get 'careers/independent'

  get 'whatwedo/social'

  get 'whatwedo/consulting'

  get 'whatwedo/technology'

  get 'home/index'

  get 'aboutus' => "home#aboutus"

  get 'whatwedo' => "home#whatwedo"

  get 'careers' => "home#careers"
  
  get 'starter' => "home#starter"
  
  get 'agrinvest' => "home#agrinvest"
  
  get 'gaae' => "home#gaae"
  
  get 'organic' => "home#organic"

  root 'home#index'

end

app/models/associate.rb
class Associate < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
end

app/models/consultant.rb
class Consultant < ActiveRecord::Base
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "My Contact Form",
      :to => "shakmog@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/independent_consultant.rb
class IndependentConsultant < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments

	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/associates_controller.rb
class AssociatesController < ApplicationController
  before_action :set_associate, only: [:show, :edit, :update, :destroy]

  # GET /associates
  # GET /associates.json
  def index
    @associates = Associate.all
  end

  # GET /associates/1
  # GET /associates/1.json
  def show
  end

  # GET /associates/new
  def new
    @associate = Associate.new
  end

  # GET /associates/1/edit
  def edit
  end

  # POST /associates
  # POST /associates.json
  def create
    @associate = Associate.new(associate_params)

    respond_to do |format|
      if @associate.save
        format.html { redirect_to @associate, notice: 'Associate was successfully created.' }
        format.json { render :show, status: :created, location: @associate }
      else
        format.html { render :new }
        format.json { render json: @associate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /associates/1
  # PATCH/PUT /associates/1.json
  def update
    respond_to do |format|
      if @associate.update(associate_params)
        format.html { redirect_to @associate, notice: 'Associate was successfully updated.' }
        format.json { render :show, status: :ok, location: @associate }
      else
        format.html { render :edit }
        format.json { render json: @associate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /associates/1
  # DELETE /associates/1.json
  def destroy
    @associate.destroy
    respond_to do |format|
      format.html { redirect_to associates_url, notice: 'Associate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_associate
      @associate = Associate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def associate_params
      params.require(:associate).permit(:surname, :other_names, :dob, :contact_add, :sec_institution, :sec_certificate, :sec_date, :uni_institution, :uni_certificate, :uni_date, :other_institution, :other_certificate, :other_date, :personal_statement, :hobbies, :telephone, :email)
    end
end

app/controllers/careers_controller.rb
class CareersController < ApplicationController
  def associate
  end

  def independent
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
  	@post = Post.find(params[:post_id])
  	@comment = @post.comments.build(comment_params)
  	@comment.save

  	redirect_to @post
  end

  def destroy
  	@comment = Comment.find(params[:id])
  	@comment.destroy

  	redirect_to @comment.post
  end

  private

  def comment_params
  	params.require(:comment).permit(:comment)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:error] = nil
      flash.now[:notice] = 'Thank you for your message!'
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def aboutus
  end

  def whatwedo
  end

  def careers
  end
 
  def starter
  end

  def agrinvest
  end

  def gaae
  end

  def organic
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  http_basic_authenticate_with name: "rendzina", password: "Rendz1na", only: :new
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :message, :avatar)
    end
end

app/controllers/whatwedo_controller.rb
class WhatwedoController < ApplicationController
  def social
  end

  def consulting
  end

  def technology
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/associates_helper.rb
module AssociatesHelper
end

app/helpers/careers_helper.rb
module CareersHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/consultants_helper.rb
module ConsultantsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/whatwedo_helper.rb
module WhatwedoHelper
end

app/views/associates/_form.html.erb
<%= simple_form_for(@associate) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :surname %>
    <%= f.input :other_names %>
    <%= f.input :dob %>
    <%= f.input :contact_add %>
    <%= f.input :sec_institution %>
    <%= f.input :sec_certificate %>
    <%= f.input :sec_date %>
    <%= f.input :uni_institution %>
    <%= f.input :uni_certificate %>
    <%= f.input :uni_date %>
    <%= f.input :other_institution %>
    <%= f.input :other_certificate %>
    <%= f.input :other_date %>
    <%= f.input :personal_statement %>
    <%= f.input :hobbies %>
    <%= f.input :telephone %>
    <%= f.input :email %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/associates/edit.html.erb
<h1>Editing associate</h1>

<%= render 'form' %>

<%= link_to 'Show', @associate %> |
<%= link_to 'Back', associates_path %>

app/views/associates/index.html.erb
<h1>Listing associates</h1>

<table>
  <thead>
    <tr>
      <th>Surname</th>
      <th>Other names</th>
      <th>Dob</th>
      <th>Contact add</th>
      <th>Sec institution</th>
      <th>Sec certificate</th>
      <th>Sec date</th>
      <th>Uni institution</th>
      <th>Uni certificate</th>
      <th>Uni date</th>
      <th>Other institution</th>
      <th>Other certificate</th>
      <th>Other date</th>
      <th>Personal statement</th>
      <th>Hobbies</th>
      <th>Telephone</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @associates.each do |associate| %>
      <tr>
        <td><%= associate.surname %></td>
        <td><%= associate.other_names %></td>
        <td><%= associate.dob %></td>
        <td><%= associate.contact_add %></td>
        <td><%= associate.sec_institution %></td>
        <td><%= associate.sec_certificate %></td>
        <td><%= associate.sec_date %></td>
        <td><%= associate.uni_institution %></td>
        <td><%= associate.uni_certificate %></td>
        <td><%= associate.uni_date %></td>
        <td><%= associate.other_institution %></td>
        <td><%= associate.other_certificate %></td>
        <td><%= associate.other_date %></td>
        <td><%= associate.personal_statement %></td>
        <td><%= associate.hobbies %></td>
        <td><%= associate.telephone %></td>
        <td><%= associate.email %></td>
        <td><%= link_to 'Show', associate %></td>
        <td><%= link_to 'Edit', edit_associate_path(associate) %></td>
        <td><%= link_to 'Destroy', associate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Associate', new_associate_path %>

app/views/associates/new.html.erb
<h1>New associate</h1>

<%= render 'form' %>

<%= link_to 'Back', associates_path %>

app/views/associates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Surname:</strong>
  <%= @associate.surname %>
</p>

<p>
  <strong>Other names:</strong>
  <%= @associate.other_names %>
</p>

<p>
  <strong>Dob:</strong>
  <%= @associate.dob %>
</p>

<p>
  <strong>Contact add:</strong>
  <%= @associate.contact_add %>
</p>

<p>
  <strong>Sec institution:</strong>
  <%= @associate.sec_institution %>
</p>

<p>
  <strong>Sec certificate:</strong>
  <%= @associate.sec_certificate %>
</p>

<p>
  <strong>Sec date:</strong>
  <%= @associate.sec_date %>
</p>

<p>
  <strong>Uni institution:</strong>
  <%= @associate.uni_institution %>
</p>

<p>
  <strong>Uni certificate:</strong>
  <%= @associate.uni_certificate %>
</p>

<p>
  <strong>Uni date:</strong>
  <%= @associate.uni_date %>
</p>

<p>
  <strong>Other institution:</strong>
  <%= @associate.other_institution %>
</p>

<p>
  <strong>Other certificate:</strong>
  <%= @associate.other_certificate %>
</p>

<p>
  <strong>Other date:</strong>
  <%= @associate.other_date %>
</p>

<p>
  <strong>Personal statement:</strong>
  <%= @associate.personal_statement %>
</p>

<p>
  <strong>Hobbies:</strong>
  <%= @associate.hobbies %>
</p>

<p>
  <strong>Telephone:</strong>
  <%= @associate.telephone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @associate.email %>
</p>

<%= link_to 'Edit', edit_associate_path(@associate) %> |
<%= link_to 'Back', associates_path %>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/contact_us/contacts/new.html.erb
<h2><%= t('.contact_us') %></h2>
<%= form_for @contact, :url => contacts_path, :html => {:class => 'formtastic'} do |f| %>
  <% if ContactUs.require_name %>
    <div class='string required' id='contact_us_contact_name_input'>
      <%= f.label :name, (t('.name') + content_tag(:abbr, '*', :class => 'required')).html_safe %>
      <%= f.text_field :name %>
      <% if f.object.errors[:name].present? %>
        <p class='inline-error'><%= f.object.errors[:name].join(' and ') %></p>
      <% end %>
    </div>
  <% end %>
  <div class='string required' id='contact_us_contact_email_input'>
    <%= f.label :email, (t('.email') + content_tag(:abbr, '*', :class => 'required')).html_safe %>
    <%= f.text_field :email %>
    <% if f.object.errors[:email].present? %>
      <p class='inline-error'><%= f.object.errors[:email].join(' and ') %></p>
    <% end %>
  </div>
  <% if ContactUs.require_subject %>
    <div class='string required' id='contact_us_contact_subject_input'>
      <%= f.label :subject, (t('.subject') + content_tag(:abbr, '*', :class => 'required')).html_safe %>
      <%= f.text_field :subject %>
      <% if f.object.errors[:subject].present? %>
        <p class='inline-error'><%= f.object.errors[:subject].join(' and ') %></p>
      <% end %>
    </div>
  <% end %>
  <div class='text required' id='contact_us_contact_message_input'>
    <%= f.label :message, (t('.message') + content_tag(:abbr, '*', :class => 'required')).html_safe %>
    <%= f.text_area :message %>
    <% if f.object.errors[:message].present? %>
      <p class='inline-error'><%= f.object.errors[:message].join(' and ') %></p>
    <% end %>
  </div>
  <div class='commit'>
    <%= f.submit :submit, :class => 'submit create', :title => t('.submit') %>
  </div>
<% end %>

app/views/contact_us/contacts/new_formtastic.html.erb
<h2><%= t('.contact_us') %></h2>
<%= semantic_form_for @contact, :url => contacts_path do |f| %>
  <%= f.input :name, :label => t('.name') if ContactUs.require_name %>
  <%= f.input :email, :label => t('.email') %>
  <%= f.input :subject, :label => t('.subject') if ContactUs.require_subject %>
  <%= f.input :message, :as => :text, :label => t('.message') %>
  <%= f.action :submit, :label => t('.submit'), :button_html => { :alt => t('.submit'), :id => 'contact_us_contact_submit', :title => t('.submit') } %>
<% end %>

app/views/contact_us/contacts/new_simple_form.html.erb
<div class="row" style="margin-top:2em;">
	<h2><%= t('.contact_us') %></h2>
	<%= simple_form_for @contact, :url => contacts_path do |f| %>
	  <%= f.input :name, :label => t('.name') if ContactUs.require_name %>
	  <%= f.input :email, :label => t('.email') %>
	  <%= f.input :subject, :label => t('.subject') if ContactUs.require_subject %>
	  <%= f.input :message, :as => :text, :label => t('.message') %>
	  <%= f.button :submit, :value => t('.submit'), :alt => t('.submit'), :id => 'contact_us_contact_submit', :title => t('.submit') %>
	<% end %>

</div>

app/views/contacts/create.html.erb
<div class="container">
	<h1>Thank you for your message.</h1>
	<p>We'll get back to you soon.</p> 
</div>

app/views/contacts/new.html.erb
<div class="container">
	<h1>Contact</h1>
	<%= simple_form_for @contact do |f| %>
		<%= f.input :name, :required => true %>
		<%= f.input :email, :required => true %>
		<%= f.input :message, :as => :text, :input_html => {:rows => 10} %>

		<%= f.button :submit, 'Send Message' %>
	<% end %>
</div>

app/views/posts/_form.html.erb
<%= simple_form_for @post, url: posts_path, html: { multipart: true } do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :message %>
    <%= f.file_field :avatar %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="container" style="margin-left:30px;">
  <h1>Rendzina Blog</h1>
  <hr>

  <% @posts.each do |post| %>
    <h4><%= link_to post.title, post %></h4>
    <% if post.avatar? %>
      <%= image_tag post.avatar.url(:medium) %>
    <% end %>
    <p><%= truncate post.message %></p>
    <p><%= time_ago_in_words post.created_at %> ago</p>  
    <p><%= post.comments.count %> comments</p>  
    <hr>
  <% end %>

  <%= link_to 'New Post', new_post_path %>
</div>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>


<h1><%= @post.title %></h1>
<% if @post.avatar? %>
  <%= image_tag @post.avatar.url %>
<% end %>
<h4><%= @post.message %></h4>

<h5>Comments</h5>
<hr>

<%= @post.comments.each do |comment| %>
	<p><%= comment.comment %></p>
	<p><%= time_ago_in_words comment.created_at %> ago</p>
	<p><%= link_to 'Delete Comment', [@post, comment], :method => :delete, :confirm => 'Are you sure?' %></p>
	<hr>
<% end %>

<%= form_for [@post, @post.comments.build] do |f| %>
	<p><%= f.text_area :comment, size: "40x10" %></p>
	<p><%= f.submit "Post Comment" %></p>
<% end %>

<p>
<%= link_to 'Back', posts_path %>

</p>