config/routes.rb
Rails.application.routes.draw do
  
  resources "contacts", only: [:new, :create]
  
  resources :consultants

  resources :associates

  get 'comments/create'

  get 'comments/destroy'

  resources :posts, :path => 'blog' do
    resources :comments
  end

  get 'careers/associate'

  get 'careers/independent'

  get 'whatwedo/social'

  get 'whatwedo/consulting'

  get 'whatwedo/technology'

  get 'home/index'

  get 'aboutus' => "home#aboutus"

  get 'whatwedo' => "home#whatwedo"

  get 'careers' => "home#careers"
  
  get 'starter' => "home#starter"
  
  get 'agrinvest' => "home#agrinvest"
  
  get 'gaae' => "home#gaae"
  
  get 'organic' => "home#organic"

  root 'home#index'

end

app/models/associate.rb
class Associate < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
end

app/models/consultant.rb
class Consultant < ActiveRecord::Base
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "My Contact Form",
      :to => "shakmog@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/independent_consultant.rb
class IndependentConsultant < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments

	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/controllers/careers_controller.rb
class CareersController < ApplicationController
  def associate
  end

  def independent
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
  	@post = Post.find(params[:post_id])
  	@comment = @post.comments.build(comment_params)
  	@comment.save

  	redirect_to @post
  end

  def destroy
  	@comment = Comment.find(params[:id])
  	@comment.destroy

  	redirect_to @comment.post
  end

  private

  def comment_params
  	params.require(:comment).permit(:comment)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:error] = nil
      flash.now[:notice] = 'Thank you for your message!'
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def aboutus
  end

  def whatwedo
  end

  def careers
  end
 
  def starter
  end

  def agrinvest
  end

  def gaae
  end

  def organic
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  http_basic_authenticate_with name: "rendzina", password: "Rendz1na", only: :new
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :message, :avatar)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/associates_helper.rb
module AssociatesHelper
end

app/helpers/careers_helper.rb
module CareersHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/consultants_helper.rb
module ConsultantsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/whatwedo_helper.rb
module WhatwedoHelper
end

app/views/layouts/_footer.html.erb
<div class="icons row">
  <div class="large-6 large-centered columns">
    <ul class="row">
      <li class="large-4 column"><a href="#"><i class="fi-social-twitter"></i></a></li>
      <li class="large-4 column"><a href="#"><i class="fi-social-facebook"></i></a></li>
      <li class="large-4 column"><a href="#"><i class="fi-social-linkedin"></i></a></li>
    </ul>
  </div>
</div>
<ul class="menu row">
  <div class="large-7 large-centered columns">
    <div class="row">
      <li class="large-3 column"><a href="/careers">Careers</a></li>
      <li class="large-3 column"><a href="#">Terms of Use</a></li>
      <li class="large-3 column"><a href="#">Privacy</a></li>
      <li class="large-3 column"><a href="/contact-us">Contact</a></li>
    </div>
  </div>
</ul>
<div id="copyright" class="container">
  <p>&copy; Rendzina Capital <%= Date.today.year %> All rights reserved.</p>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 5 %>
<nav>
	<div id="header-wrapper">
		<div id="header" class="container">
			<div id="logo">
				<%= link_to image_tag("rendzina_logo.png"), root_path %>
      			<%= render 'layouts/navigation_links' %>
			</div>
		</div>
	</div>
	<div id="header-featured">
		<a href="#"><i class="fi-social-twitter"></i></a>
		<a href="#"><i class="fi-social-facebook"></i></a>
		<a href="#"><i class="fi-social-linkedin"></i></a>
		<div id="featured_contact">
			<i class="fi-telephone">  +2349098969919</i>
			<%= link_to 'Send an Inquiry', new_contact_path %>
		</div>
		
	</div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<div id="menu">
	<ul>
		<li class="current_page_item"><%= link_to 'Home', root_path %></li>
		<li><%= link_to 'About Us', aboutus_path %></li>
		<li><%= link_to 'What We Do', whatwedo_path %></li>
		<li><%= link_to 'Blog', posts_path %></li>
		<li><%= link_to 'Careers', careers_path %></li>
		<!-- <li><%= link_to 'Contact Us', contact_us_path %></li> -->
	</ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Rendzina Capital" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rendzina Capital" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag 'vendor/modernizr' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <div id="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </div>
    <footer>
      <%= render 'layouts/footer' %>
    </footer>
  </body>
</html>